function res = ballForceRadial(obj, X_1, X_2, A_1, A_2, delta_i,...
    delta_o, f_i, f_o, lambda_o, lambda_i, D, ...
    K_o, K_i, d_m, sin_alp_i, cos_alp_i,...
    sin_alp_o, cos_alp_o, M_g, gamma_tick, omega,...
    m_ball, rc_id)
F_c = centrifugalForce(obj, d_m, omega, sin_alp_i, cos_alp_i,...
    sin_alp_o, cos_alp_o, gamma_tick, m_ball, rc_id);
res = (...
    (K_o.*engPower(delta_o,1.5).*X_2)...
    + ((lambda_o*M_g.*X_1)/D)...
    )...
    ./((f_o-0.5)*D+delta_o)...
    -...
    ( ...
    (K_i.*engPower(delta_i,1.5).*(A_2-X_2))...
    +((lambda_i*M_g)/D.*(A_1-X_1)) ...
    )...
    ./((f_i-0.5)*D+delta_i)...
    -F_c;
end
