function obj = BallBearing()
obj.geometry=struct(...
    'D',0,...
    'd_m',0,...
    'alpha_free',0,...
    'r_i',0,'r_o',0,...
    'z',0,...
    'psi',0,...
    'f_i',0,'f_o',0,...
    'gamma_tick',0,...
    'R_i',0,...
    'set',0);
obj.physical=struct(...
    'rho_ball',0,...
    'E_I',0,'E_II',0,...
    'xi_I',0,'xi_II',0,...
    'm_ball',0,...
    'J_ball',0,...
    'set',0);
obj.lubrication=struct(...
    'eta_0',0.03,... % 基础粘度 [Pa.s] (公式 2-17,2-18)
    'alpha',2.2e-8,... % 粘压系数 [Pa^-1] (公式 2-18)
    'gamma_pv',0.04,... % 粘温系数 [K^-1] (公式 2-18,2-19)
    'tau_y',100,... % 屈服剪切应力 [Pa] (Palacios公式 2-17)
    'phi',0.01,... % 塑性粘度 [Pa.s] (公式 2-17)
    'n_shear',0.5,... % 剪切速率指数 [-] (公式 2-17)
    'Kc',0.15,... % 润滑剂热导率 [W/(m.K)] (公式 2-19)
    'rho',980,... % 润滑脂密度 [kg/m^3]
    'grease_ratio',0.3,... % 润滑脂比例系数 X [-] (公式 2-33)
    'Cd',0.44,... % 拖曳阻力系数 [-] (公式 2-32)
    'set',0);
obj.cage=struct(...
    'clearance',1e-4,... % 兜孔间隙 Cp [m] (公式 2-24)
    'D_p',0,... % 兜孔直径 [m] (Cp = 0.5*(D_p - D))
    'K_n',1e9,... % 接触刚度 [N/m^1.5] (公式 2-24)
    'mass',0.005,... % 保持架质量 [kg] (典型值 5g)
    'omega_c',0,... % 保持架角速度 [rad/s] (公式 2-23)
    ... % 流体动力学参数 (公式 2-25 ~ 2-31)
    'R_outer',0.012,... % 保持架外圆表面半径 R₁ [m] (典型值 12mm)
    'guide_width',0.003,... % 引导面宽度 L [m] (典型值 3mm)
    'guide_clearance',5e-5,... % 引导间隙 C₁ [m] (典型值 50μm)
    'epsilon_c',0,... % 相对偏心率 ε_c [-] (公式 2-27)
    'delta_yc',0,... % Y方向偏移 [m] (公式 2-31)
    'delta_zc',0,... % Z方向偏移 [m] (公式 2-31)
    'set',0);
end
