function res = ballForceAxial(X_1, X_2, A_1, A_2, delta_i,...
    delta_o, f_i, f_o, lambda_o, lambda_i, D, K_o, K_i, M_g)
res = (((lambda_o*M_g.*X_2)/D) - (K_o.*engPower(delta_o,1.5).*X_1))...
    ./((f_o-0.5)*D+delta_o)...
    + ( ...
    (K_i.*engPower(delta_i,1.5).*(A_1-X_1))...
    -((lambda_i*M_g)/D.*(A_2-X_2)) ...
    )...
    ./((f_i-0.5)*D+delta_i);
end
