function omega_R = ballSpinSpeed(sin_alp_i, cos_alp_i, sin_alp_o,...
    cos_alp_o, omega, gamma_tick, beta)
%Calculates the spinning speed of the balls.
omega_R=-omega./...
    (...
    (...
    (cos_alp_o+tand(beta).*sin_alp_o)...
    ./(1+gamma_tick*cos_alp_o)...
    +...
    (cos_alp_i+tand(beta).*sin_alp_i)...
    ./(1-gamma_tick*cos_alp_i)...
    )...
    *gamma_tick.*cosd(beta)...
    );
end
