function res = bendingMoment(X_1, X_2, A_1, A_2, delta_i, M_g,...
    D, K_i, f_i, lambda_i, M, trig_psi, R_i)
if precise
    res= M - ballsum(vpa(...
        (...
        (...
        (...
        (...
        (K_i.*(A_1-X_1).*engPower(delta_i,1.5))...
        -...
        ((lambda_i*M_g)/D.*(A_2-X_2))...
        )*R_i...
        )...
        ./...
        (...
        (f_i-0.5)*D+delta_i...
        )...
        )...
        + lambda_i*f_i*M_g...
        )...
        .*trig_psi));
else
    res= M - ballsum(...
        (...
        (...
        (...
        (...
        (K_i.*(A_1-X_1).*engPower(delta_i,1.5))...
        -...
        ((lambda_i*M_g)/D.*(A_2-X_2))...
        )*R_i...
        )...
        ./...
        (...
        (f_i-0.5)*D+delta_i...
        )...
        )...
        + lambda_i*f_i*M_g...
        )...
        .*trig_psi);
end
end
