function res = forceRadial(X_1, X_2, A_1, A_2, delta_i,...
    K_i, lambda_i, D, f_i, F_r, M_g, trig_psi)
if precise
    res = F_r - ballsum(vpa((...
        (...
        K_i.*(A_2-X_2).*engPower(delta_i,1.5) ...
        +(lambda_i*M_g)/D.*(A_1-X_1)...
        )...
        ./((f_i-0.5)*D+delta_i) ...
        ).*trig_psi));
else
    res = F_r - ballsum((...
        (...
        K_i.*(A_2-X_2).*engPower(delta_i,1.5) ...
        +(lambda_i*M_g)/D.*(A_1-X_1)...
        )...
        ./((f_i-0.5)*D+delta_i) ...
        ).*trig_psi);
end
end
