function res = forceAxial(X_1, X_2, A_1, A_2, delta_i,...
    K_i, lambda_i, D, f_i, F_a, M_g)
if precise %switch to activate rounding after addition.
    %May help with some numerical problems.
    res = F_a - ballsum(vpa(...
        (...
        K_i.*(A_1-X_1).*engPower(delta_i,1.5) ...
        -(lambda_i*M_g)/D.*(A_2-X_2)...
        )...
        ./((f_i-0.5)*D+delta_i) ...
        ));
else
    res = F_a - ballsum(...
        (...
        K_i.*(A_1-X_1).*engPower(delta_i,1.5) ...
        -(lambda_i*M_g)/D.*(A_2-X_2)...
        )...
        ./((f_i-0.5)*D+delta_i) ...
        );
end
end
