function solvStruct = genSolvStruct(valueVec, geo)
%genSolvStruct 从求解向量生成结构体
%   状态向量结构 (完整公式2-53实现):
%   [X1(z), X2(z), di(z), do(z), beta(z), beta_prime(z), omega_b(z),
%    globals(5), cage(3)]

num_ball_vars = 7;  % 每球7个变量
num_global_vars = 5;
num_cage_vars = 3;  % 保持架3个变量 (公式 2-53)

% 分割变量向量
ball_vals = valueVec(1 : geo.z * num_ball_vars);
global_vals = valueVec(geo.z * num_ball_vars + 1 : geo.z * num_ball_vars + num_global_vars);
cage_vals = valueVec(end - num_cage_vars + 1 : end);

valMat = reshape(ball_vals, round(geo.z), num_ball_vars)';

solvStruct = struct(...
    'X_1', valMat(1,:)'+sind(geo.alpha_free)*(geo.f_o-0.5)*...
    geo.D*ones(geo.z,1),...
    'X_2', valMat(2,:)'+cosd(geo.alpha_free)*(geo.f_o-0.5)*...
    geo.D*ones(geo.z,1),...
    'delta_i', valMat(3,:)',...
    'delta_o', valMat(4,:)',...
    'beta', valMat(5,:)',...          % 姿态角 β [deg]
    'beta_prime', valMat(6,:)',...    % 偏转角 β' [deg]
    'omega_b', valMat(7,:)',...       % 自转速度 [rad/s]
    'delta_a', global_vals(1),...
    'delta_ry', global_vals(2),...
    'delta_rz', global_vals(3),...
    'M_y', global_vals(4)*1e4,...
    'M_z', global_vals(5)*1e4,...
    ... % 保持架变量 (公式 2-53)
    'delta_yc', cage_vals(1),...      % 保持架Y方向偏移 [m]
    'delta_zc', cage_vals(2),...      % 保持架Z方向偏移 [m]
    'omega_c', cage_vals(3));         % 保持架角速度 [rad/s]
end
