function [err, jac] = hertzError(kappa, rho)
%Funciton to nummerically solve the herzian contact ellipsoid.
%This is a lot slower than using the correlation, which is also
%included in this class.
F_rho_dir = ((rho(:,1)-rho(:,2))+(rho(:,3)-rho(:,4)))...
    ./sum(rho,2);

[F, E] = ellipke(1-1./kappa.^2);
%Non-Standard definition of the input parameter:
%   m{matlab}=k^2{wikipedia}=1-1/kappa^2{Harris}
F_rho_indir=((kappa.^2+1).*E-2*F)./((kappa.^2-1).*E);
err=F_rho_dir-F_rho_indir;
jac=diag((2*(F.^2 + 3*kappa.^2.*E.^2 - 2*E.*F -...
    2*kappa.^2.*E.*F))./(kappa.*E.^2.*(kappa.^2 - 1).^2));
%           Jacobi matrix generated by the following symmath:
%             clear;
%             syms kappa
%             [F, E] = ellipke(1-1./kappa.^2);
%             F_rho_indir=((kappa.^2+1).*E-2*F)./((kappa.^2-1).*E);
%             simplify(diff(-F_rho_indir, kappa))
end
