% Test file for jPat.m
% Autogenerated by GeminCode Assistant
% clear; clc; % Commented out for batch execution

% --- Define Inputs ---
z = 14;

% --- Call Function ---
[res] = jPat(z);

% --- Display Results ---
disp('Testing jPat...');
disp('res:');
disp(res);
