function loadStruct = makeLoad(loadArray)
loadStruct=struct(...
    'F_a',loadArray(1), ...
    'F_ry',loadArray(2), ...
    'F_rz',loadArray(3), ...
    'Theta_y',loadArray(4), ...
    'Theta_z',loadArray(5), ...
    'n', loadArray(6)...
    );
end
