function A_1 = raceCenterDistAx(delta_a, geo, load)
A_1 = (geo.f_i+geo.f_o-1)*geo.D*sind(geo.alpha_free)...
    + delta_a + ...
    load.Theta_y*geo.R_i*cosd(geo.psi)+...
    load.Theta_z*geo.R_i*sind(geo.psi)+...
    geo.Delta_P_D;
if ~isreal(A_1)
    disp('A_1 complex')
end
end
