% Test file for raceCenterDistRad.m
% Autogenerated by GeminCode Assistant

% --- Define Inputs ---
D = 4.7625e-3;
dm = 20e-3;
fi = 0.52; fo = 0.52;
alpha_free = 15;
Z = 14;

% Properly construct geo struct with required fields
geo = struct();
geo.D = D;
geo.f_i = fi;
geo.f_o = fo;
geo.alpha_free = alpha_free;
geo.psi = (0:Z-1)' * 360/Z; % Function uses cosd/sind

delta_ry = 1e-6;
delta_rz = 1e-6;

% --- Call Function ---
A_2 = raceCenterDistRad(delta_ry, delta_rz, geo);

% --- Display Results ---
disp('Testing raceCenterDistRad...');
disp(['A_2 (mean): ', num2str(mean(A_2))]);
disp(['A_2 size: ', num2str(size(A_2, 1)), 'x', num2str(size(A_2, 2))]);
